title:  "Too Much Gyan"
tagline: ""
description:
author:
  name: ""
  twitter: 

menu:
- {name: '', file: ''}

social:
- {icon: '', link: ''}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
